#version 450

layout(local_size_x = 16, local_size_y = 16) in;

layout(push_constant) uniform push_constants {
    vec4 col;
} constants;

layout(set = 0, binding = 0, rgba8) uniform writeonly image2D img;

void main() {
    imageStore(img, ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y), vec4(float(gl_GlobalInvocationID.x) / 1280, constants.col.x, float(gl_GlobalInvocationID.y) / 720, 1));
}