#version 450

layout(local_size_x = 16, local_size_y = 16) in;

layout(push_constant) uniform push_constants {
    mat4 view;
    vec3 pos;
    int downscale;
    int tri_count;
} scene;

struct tri {
    vec3 verts[3];
    vec3 normal;
    vec3 col;
    uint mesh_id;
    uint a;
    uint b;
    uint c;
};

layout(std140, set = 0, binding = 0) readonly buffer Objects {
    tri tris[];
} objs;

layout(set = 0, binding = 1, rgba8) uniform writeonly Image img;

void main() {
    imageStore(img, ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y), vec4(float(gl_GlobalInvocationID.x) / 1280, 0, float(gl_GlobalInvocationID.y) / 720, 1));
}